services:
  postgres-stripe:
    image: postgres:17-alpine
    container_name: postgres_stripe_container
    environment:
      POSTGRES_DB: stripe_db
      POSTGRES_USER: stripe
      POSTGRES_PASSWORD: stripe
    ports:
      - "5432:5432"
